spring:
  application:
    name: variation-config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    publisher-confirms: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangchangsheng005/chaos-variation.git
          search-paths: /**  # 指定搜索根路径下的所有目录，若有多个路径使用逗号隔开
          username: wangchangsheng005  #账号密码写真实的快一些我觉得，不使用也能访问有点慢
          password: Wcs=123456

server:
  port: 8206

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8200/eureka/

